#!/bin/bash
EVENT=$(cat)

COMMAND=$(echo "$EVENT" | jq -r '.tool_input.command // ""')

# Only trigger for test commands
if ! echo "$COMMAND" | grep -qiE "test|cy:run|cypress|jest|vitest|gradlew.*test|pytest|mocha"; then
  exit 0
fi

CWD=$(echo "$EVENT" | jq -r '.cwd // "."')
EXIT_STATUS=$(echo "$EVENT" | jq -r '.tool_response.exit_status // "unknown"')
OUTPUT=$(echo "$EVENT" | jq -r '.tool_response.result // "No output captured"')
DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date +"%B %d, %Y %H:%M")

REPORT_DIR="$CWD/reports"
mkdir -p "$REPORT_DIR"

# Parse test counts from output (works for Gradle/Jest/Cypress)
TOTAL=$(echo "$OUTPUT" | grep -oiE '[0-9]+ tests?' | head -1 | grep -oE '[0-9]+' || echo "0")
PASSED=$(echo "$OUTPUT" | grep -oiE '[0-9]+ (passed|succeeded|successful)' | head -1 | grep -oE '[0-9]+' || echo "0")
FAILED=$(echo "$OUTPUT" | grep -oiE '[0-9]+ (failed|failures?)' | head -1 | grep -oE '[0-9]+' || echo "0")
SKIPPED=$(echo "$OUTPUT" | grep -oiE '[0-9]+ (skipped|ignored|pending)' | head -1 | grep -oE '[0-9]+' || echo "0")

# Fallback: if total is 0 but passed/failed exist, compute total
if [ "$TOTAL" = "0" ] && [ "$PASSED" != "0" -o "$FAILED" != "0" ]; then
  TOTAL=$((PASSED + FAILED + SKIPPED))
fi

# Get git info
BRANCH=$(cd "$CWD" && git branch --show-current 2>/dev/null || echo "unknown")
COMMIT=$(cd "$CWD" && git log -1 --pretty=format:"%h - %s" 2>/dev/null || echo "unknown")

# Determine project name
PROJECT="unknown"
if [ -f "$CWD/package.json" ]; then
  PROJECT=$(jq -r '.name // "unknown"' "$CWD/package.json")
elif [ -f "$CWD/settings.gradle" ]; then
  PROJECT=$(grep -oP "rootProject.name\s*=\s*'\\K[^']+" "$CWD/settings.gradle" 2>/dev/null || echo "unknown")
fi

# Pass rate
if [ "$TOTAL" -gt 0 ] 2>/dev/null; then
  PASS_RATE=$(awk "BEGIN {printf \"%.1f\", ($PASSED/$TOTAL)*100}")
else
  PASS_RATE="0.0"
fi

# Verdict
if [ "$FAILED" = "0" ] && [ "$(echo "$PASS_RATE >= 95" | bc -l 2>/dev/null || echo 0)" = "1" ]; then
  VERDICT="Safe to release"
  VERDICT_COLOR="#639922"
  VERDICT_BG="#EAF3DE"
elif [ "$(echo "$PASS_RATE >= 85" | bc -l 2>/dev/null || echo 0)" = "1" ]; then
  VERDICT="Release with caution"
  VERDICT_COLOR="#EF9F27"
  VERDICT_BG="#FAEEDA"
else
  VERDICT="Do not release"
  VERDICT_COLOR="#E24B4A"
  VERDICT_BG="#FCEBEB"
fi

REPORT_FILE="$REPORT_DIR/test-report-${DATE}.md"

cat > "$REPORT_FILE" << REPORT
# Test Report — $PROJECT

**Date:** $TIMESTAMP
**Branch:** $BRANCH
**Commit:** $COMMIT
**Verdict:** $VERDICT

---

## Executive Summary

$TOTAL tests were executed. $PASSED passed, $FAILED did not pass, and $SKIPPED were skipped.
The overall pass rate is ${PASS_RATE}%.

**Recommendation: $VERDICT**

---

## Test Execution Summary

| Metric   | Count |
|----------|-------|
| Total    | $TOTAL |
| Passed   | $PASSED |
| Failed   | $FAILED |
| Skipped  | $SKIPPED |
| Pass Rate| ${PASS_RATE}% |

---

## Command

\`\`\`
$COMMAND
\`\`\`

## Test Output

\`\`\`
$OUTPUT
\`\`\`

---

*Generated by Kiro QA Hook · $PROJECT · Confidential*
REPORT

# Update history.json
HISTORY_FILE="$REPORT_DIR/history.json"
NEW_ENTRY="{\"date\":\"$DATE\",\"project\":\"$PROJECT\",\"total\":$TOTAL,\"passed\":$PASSED,\"failed\":$FAILED,\"skipped\":$SKIPPED,\"passRate\":$PASS_RATE,\"verdict\":\"$VERDICT\"}"

if [ -f "$HISTORY_FILE" ]; then
  # Append and keep last 10
  UPDATED=$(jq --argjson entry "$NEW_ENTRY" '. + [$entry] | .[-10:]' "$HISTORY_FILE" 2>/dev/null)
  if [ $? -eq 0 ]; then
    echo "$UPDATED" > "$HISTORY_FILE"
  fi
else
  echo "[$NEW_ENTRY]" | jq '.' > "$HISTORY_FILE"
fi

echo "✓ Report: $REPORT_FILE" >&2
echo "✓ History: $HISTORY_FILE" >&2

exit 0
